name: 'Run Python Script'
description: 'Run a Python script and output a result'

inputs:
  version:
    required: false
  note:
    required: false
outputs:
  result:
    description: 'Result from script'
runs:
  using: 'composite'
  steps:
    - run: |
        python3 ${{ github.action_path }}/script.py "${{ inputs.version }}" "${{ inputs.note }}" > result.txt
        echo "result=$(cat result.txt)" >> $GITHUB_OUTPUT
      shell: bash
