name: Gateway Router Cross-Repo

on:
  workflow_dispatch:
    inputs:
      workflow:
        description: 'Select workflow to trigger'
        type: choice
        required: true
        options: [ci, cd]
      branch:
        description: 'Target branch'
        type: choice
        required: true
        options: [dev, test, prod]
      version:
        description: 'Release version'
        required: true
        type: string
      note:
        description: 'Trigger note or remarks'
        required: false
        type: string

permissions:
  actions: write
  contents: read

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow_dispatch on target branch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: `${{ inputs.workflow }}.yml`,
              ref: `${{ inputs.branch }}`,
              inputs: {
                version: `${{ inputs.version }}`,
                note: `${{ inputs.note || '' }}`
              }
            });
